version: 2
jobs:
  build:
    docker:
      - image: cimg/node:12.18-browsers

    steps:
      - checkout

      - run: npm install

      - run:
          name: Download Selenium
          command: sudo npm install selenium-standalone@6.17.0 -g
      - run:
          name: Start Selenium
          command: selenium-standalone install && selenium-standalone start
          background: true

      - run:
          name: Functional tests
          command: npm run test-func

      - store_artifacts:
          path: hermione-report/
          destination: /hermione-report
